import Head from "next/head";
import { Inter } from "next/font/google";
import Dashboard from "@/components/dashboard";
import { Provider } from "react-redux";
import store from "@/service/store";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Provider store={store}>
          <Dashboard />
        </Provider>
      </main>
    </>
  );
}
